# fly.toml app configuration file generated for fieldiq-api on 2026-06-07T08:55:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fieldiq-api'
primary_region = 'ams'

[build]
  dockerfile = 'backend/Dockerfile'

[env]
  LIVE_DATA_PROVIDER = 'mock'
  PORT = '8080'
  PYTHONUNBUFFERED = '1'
  SERVE_FRONTEND = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 512
